interlayer/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings

from typing import Pattern
from crudapp import views

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django_filters.views import FilterView
admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path("accounts/", include("django.contrib.auth.urls")),

    path('api/',include('myapi.urls')),
    #path('atms/', views.IndexView.as_view(), name='atms'),
    path('atms/', views.TestAtmView.as_view(), name='atms'),
    path('', views.IndexPage, name='index'),
    path('atms/statistic/', views.atmStatistic, name='static'),
    path('atms/<int:pk>/', views.AtmDetailView.as_view(), name='detail'),
    path('atms/edit/<int:pk>/', views.edit, name='edit'),
    path('atms/create/', views.create, name='create'),
    path('atms/delete/<int:pk>/', views.delete, name='delete'),
    path('atms/photo/upload/', views.image_upload_view, name='photo-upload'),
    path('atms/photo/upload/<int:pk>/', views.image_upload_view, name='photo-upload-num'),

    path('ticket/<int:pk>/', views.TicketView, name='ticket'),
    #path('ticket/<int:pk>/', views.TicketView.as_view(), name='ticket'),

    
    path('model/', views.ModelAtmView.as_view(), name='model-list'),
    path('model/create', views.modelCreate, name='model-create'),
    path('model/delete/<int:pk>/', views.modelDelete, name='model-delete'),
    path('model/edit/<int:pk>/', views.modelEdit, name='model-edit'),
    path('function/', views.FunctionModelAtmView.as_view(), name='function-list'),
    path('function/create', views.functionCreate, name='function-create'),
    path('function/delete/<int:pk>/', views.functionDelete, name='function-delete'),
    path('function/edit/<int:pk>/', views.functionEdit, name='function-edit'),
    path('tse/', views.ModelTseView.as_view(), name='tse-list'),
    path('tse/status/<int:pk>/', views.regtseStatusChange, name='regtse-status-change'),
    path('device/', views.ModelDeviceView.as_view(), name='device-list'),
    path('request/', views.ModelRequestView.as_view(), name='request-list'),
    path('request/<int:pk>/', views.requestShow, name='request-full'),
    path('device/status/<int:pk>/', views.regdevStatusChange, name='regdev-status-change'),
    path('profile/', views.profile, name='users-profile'),
    path('password-change/', views.ChangePasswordView.as_view(), name='password-change'),

    path('servicedesk/', views.ModelTicketView.as_view(), name='servicedesk'),
    path('servicedesk/closed/', views.ModelTicketClosedView.as_view(), name='servicedesk-close'),
    path('servicedesk/atm/<int:id>/', views.ModelTicketAtmView.as_view(), name='servicedesk-atm'),
    path('servicedesk/users/', views.ModelTicketUsersView.as_view(), name='servicedesk-users'),
    path('pcipts/', views.ModelPCIPTSView.as_view(), name='pcipts'),
    path('test/tse/', views.ModelTseTestView.as_view(), name='tse-list-test'),
    path('test/tse/status/<int:pk>/', views.regtseTestStatusChange, name='regtse-status-change-test'),
    path('test/device/', views.ModelDeviceTestView.as_view(), name='device-list-test'),
    path('test/request/', views.ModelRequestTestView.as_view(), name='request-list-test'),
    path('test/request/<int:pk>/', views.requestTestShow, name='request-full-test'),
    path('test/device/status/<int:pk>/', views.regdevTestStatusChange, name='regdev-status-change-test'),
    path('export/csv/', views.export_report_csv, name='export_report_csv'),
    path('telegramapi/', views.telegramApi, name='telegramApi'),
    path('tg/users/<int:pk>/<int:mfo>/', views.tgUserChangeMfo, name='tg-user-change'),
    #path('search/', views.FilterView.as_view(filterset_class=AtmFilter, template_name='crudapp/atms-filter-list.html'), name='searcher'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

myapi/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Payment Transfer API
    path('ReceivingData/', views.ReceivingData, name='ReceivingData'),
    path('ReceivingDataTest/', views.ReceivingDataTest, name='ReceivingDataTest'),
]

crudapp/models.py
from django.conf import settings
from django.db import models
from datetime import date, datetime, timezone
from django.forms.widgets import RadioSelect
from django.db.models.fields import NullBooleanField
from django.contrib.auth.models import User
from PIL import Image

#Филиалы
class MfoStruct(models.Model):
    name = models.CharField("Название", max_length=255, default='', blank = True, null = True)
    number = models.IntegerField("МФО", blank = True, null = True)

    class Meta:
        verbose_name = "MFO"
        verbose_name_plural = "MFO"

    def __str__(self):
        if not self.number or not self.name:
            return 'unknown'
        return self.name+' ('+str(self.number).zfill(5)+')'


class AtmModelFunction(models.Model):
    name = models.CharField("Название", max_length=255,blank = True, null = True)
    html = models.TextField(blank = True, null = False)
    description = models.TextField(blank = True, null = True)

    class Meta:
        verbose_name = "Параметр"
        verbose_name_plural = "Параметры"

    def __str__(self):
        return self.name

class AtmModel(models.Model):
    name = models.CharField("Название", max_length=255,blank = True, null = True)
    company = models.CharField("Компания", max_length=255,blank = True, null = True)
    image = models.ImageField("Изображение", upload_to='model/model_img_'+datetime.now().strftime("%Y%m%d_%H-%M-%S"), blank=True, null = True)
    functions = models.ManyToManyField(AtmModelFunction, blank=True, verbose_name="Функционал")

    class Meta:
        verbose_name = "Модель ATM"
        verbose_name_plural = "Модели ATM"

    def __str__(self):
        return self.name

class serviceContract(models.Model):
    SERVICEDESK = (
        (0, 'Гарантийное'),
        (1, 'Сервисное'),
        (2, 'Отсуствует'),
    )
    name = models.CharField("Договор", max_length=255)
    dataBegin = models.DateField("Дата начала", blank = True, null = True)
    dataEnd = models.DateField("Дата конца", blank = True, null = True)
    company = models.CharField("Компания", max_length=255,blank = True, null = True)
    type = models.IntegerField("Вид", choices=SERVICEDESK, default=0)
    amt = models.FloatField("Стоимость", default=0, blank = True, null = True)

    def __str__(self):
        if self.dataEnd:
            return '{0} ({1}) - {2}'.format(self.name ,self.get_type_display(),self.dataEnd)
        return  '{0} ({1})'.format(self.name ,self.get_type_display())
    
    
    class Meta:
        verbose_name = "Сервис Компании"
        verbose_name_plural = "Сервис Компании"

#terminalId
class Atm(models.Model):
    AUTH_PROC = (
        (0, 'Внешний процессинг'),
        (1, 'Внутренний процессинг'),
    )
    SEL = (
        (0, 'Off'),
        (1, 'On'),
    )
    WT = (
        (0, '24/7'),
        (1, '09:00-18:00'),
        (2, '08:00-23:00'),
        (3, '08:00-01:00'),
    )
    name = models.CharField("Название", max_length=255,blank = True, null = True)
    serialNumber = models.PositiveBigIntegerField("Серийный номер")
    merchantId = models.CharField("Merchant ID", default='', max_length=255, blank = True, null = True)
    atmModelId = models.ForeignKey(verbose_name="Модель банкомата", to=AtmModel, on_delete=models.CASCADE)
    description = models.TextField("Описание", blank = True, null = True)
    createdAt = models.DateTimeField("Created At", auto_now_add = True)
    terminalId = models.CharField("Terminal ID", max_length=255, blank = True, null = True)
    mfo = models.ForeignKey(MfoStruct, on_delete=models.CASCADE)
    lat = models.FloatField(default=0.,blank = True, null = True)
    long = models.FloatField(default=0.,blank = True, null = True)
    mobile = models.TextField("Sim", blank = True, null = True)
    exDate = models.DateField("Эксплуатация", blank = True, null = True)
    inBankProcessing = models.IntegerField("Процессинговый центр", default = 0, choices=AUTH_PROC)
    NFC = models.IntegerField("NFC", default = 0, choices=SEL)
    RDSCommander = models.IntegerField("RDS Commander", default = 0, choices=SEL)
    service = models.ForeignKey(verbose_name="Обслуживание", to=serviceContract, null = True, on_delete=models.CASCADE)
    workTime = models.IntegerField("Время работы", default=0, choices=WT)

    class Meta:
        verbose_name = "Банкомат"
        verbose_name_plural = "Банкоматы"

    def __str__(self):
        return self.name
#{% for group_for in request.user.groups.all %}/{{group_for.name}}{% endfor %}
class AtmImage(models.Model):
    title = models.CharField(max_length=200, default="atm_img_"+datetime.now().strftime("%Y%m%d_%H-%M-%S"), null = True, blank=False)
    description = models.TextField(null = True, blank=True)
    image = models.ImageField(upload_to='atms/%Y/%m/%d/', blank=False)
    atmId = models.ForeignKey(related_name='atms', to=Atm, on_delete=models.CASCADE)
    uploadedAt = models.DateTimeField("uploadedAt", auto_now_add = True)

    class Meta:
        verbose_name = "Изображение"
        verbose_name_plural = "Изображения"

    def __str__(self):
        return self.title

class brokenCategory(models.Model):
    title = models.CharField(max_length=128)
    local_uz = models.CharField(max_length=128,null=True, blank=True)
    local_ru = models.CharField(max_length=128,null=True, blank=True)
    local_en = models.CharField(max_length=128,null=True, blank=True)
    description = models.TextField(null=True,blank=True)
    description_uz = models.TextField(null=True,blank=True)
    description_ru = models.TextField(null=True,blank=True)
    description_en = models.TextField(null=True,blank=True)
    priority = models.FloatField(default=0.,null=True, blank=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = "Категории поломок"
        verbose_name_plural = "Категории поломок"



class telegramUser(models.Model):
    AUTH_CHOICES = (
        (0, 'Неавторизован'),
        (1, 'Авторизован'),
    )
    LANG_CHOICES = (
        (0, 'Узбекский'),
        (1, 'Русский'),
    )
    uid = models.IntegerField(default=0, verbose_name='Telegram User ID')
    mfo = models.ForeignKey( MfoStruct, default=None, blank=True, null=True, on_delete=models.CASCADE, verbose_name='Филиал')
    name = models.CharField("Имя", max_length=255,blank = True, null = True)
    stage = models.TextField(blank=True, null=True, default='', verbose_name='Действие')
    status = models.IntegerField(default=0, choices=AUTH_CHOICES, verbose_name='Авторизация')
    json_info = models.TextField(blank=True, null=True, default='', verbose_name='JSON')
    language = models.IntegerField(default=0, choices=LANG_CHOICES, verbose_name='Локализация') 

    def __str__(self):
        if not self.mfo:
            return str(self.uid)+' - '+self.name+' [not mfo]'
        return str(self.uid)+' - '+self.name+' ['+str(self.mfo.name)+']'


    class Meta:
        verbose_name = "Телеграм Пользователи"
        verbose_name_plural = "Телеграм Пользователи"

class ticket(models.Model):
    STATUS_CHOICES = (
        (0, 'Открыто'),
        (1, 'Закрыто'),
        (2, 'Отменено'),
        (3, 'Сервисное обслуживание'),
        (4, 'В работе'),
        (5, 'Неизвестно'),
    )
    broken = models.ManyToManyField(brokenCategory, blank=True, verbose_name="Проблема")
    atm = models.ForeignKey(Atm, default=None, blank=True, null=True, on_delete=models.CASCADE, verbose_name='Банкомат')
    user = models.ForeignKey(telegramUser, default=None, blank=True, null=True, on_delete=models.CASCADE, verbose_name='Пользователь (Telegram)')
    dataCreated = models.DateTimeField(default=datetime.now, blank=True, verbose_name='Создан')
    dataClosed = models.DateTimeField(null=True, blank=True, verbose_name='Закрыт')
    status = models.IntegerField(choices=STATUS_CHOICES, null=True, blank=True, default=5, verbose_name='Статус')
    operator = models.TextField(blank=True, null=True, default='', verbose_name='Модератор')
    description = models.TextField(blank=True, null=True, default='', verbose_name='Комментарий')
    edited = models.IntegerField(null=True, blank=True, default=0, verbose_name='Редактирование')

    def save(self):
        self.dataClosed = datetime.now()
        super(ticket, self).save()

    class Meta:
        verbose_name = "Тикеты"
        verbose_name_plural = "Тикеты"

class telegramMsg(models.Model):
    json = models.TextField()
    text = models.BinaryField(blank=True, null=True)
    caption = models.BinaryField(null=True, blank=True) 
    t = models.ForeignKey(related_name='ticket', to=ticket, default=None, blank=True, null=True, on_delete=models.CASCADE)
    category = models.TextField(default='')
    dt = models.DateTimeField(default=datetime.now, blank=True)
    path = models.TextField(default='', blank=True)
    download = models.BooleanField(default=False)
    operator = models.BooleanField(default=False)
    show = models.BooleanField(default=False)

class chatHistory(models.Model):
    chat = models.BigIntegerField(default=0)
    user = models.BigIntegerField(default=0)
    message_id = models.BigIntegerField(default=0)


class PCIPTS(models.Model):
    manufacturer_name = models.TextField("Компания",blank=True, null=True, default='')
    model_name = models.TextField(blank=True, null=True, default='')
    hardware_number = models.TextField(blank=True, null=True, default='')
    firmware_number = models.TextField(blank=True, null=True, default='')
    application_number = models.TextField(blank=True, null=True, default='')
    approval_number = models.TextField(blank=True, null=True, default='')
    version = models.TextField(blank=True, null=True, default='')
    approval_class = models.TextField("Наименование",blank=True, null=True, default='')
    product_type = models.TextField(blank=True, null=True, default='')
    expiry_date = models.DateField(default=datetime.now, blank=True)
    approval_class_1 = models.TextField(blank=True, null=True, default='')

crudapp/forms.py
from django import forms
from .models import Atm, AtmImage, AtmModel, AtmModelFunction, ticket, User, Profile

class AtmForm(forms.ModelForm):
    class Meta:
        model = Atm
        fields = ( 'name', 'serialNumber', 'merchantId', 'atmModelId', 'description', 'terminalId', 'mfo','inBankProcessing', 'RDSCommander','service', 'NFC','workTime', 'lat','long' )


class AtmImageForm(forms.ModelForm):
    class Meta:
        model = AtmImage
        fields = ('title', 'image', 'description', 'atmId')

class AtmModelForm(forms.ModelForm):
    class Meta:
        model = AtmModel
        fields = "__all__"

class AtmModelFunctionForm(forms.ModelForm):
    class Meta:
        model = AtmModelFunction
        fields = "__all__"

class ticketStatusForm(forms.ModelForm):
    def __init__(self,mfo,*args,**kwargs):
        super (ticketStatusForm,self ).__init__(*args,**kwargs) # populates the post
        self.fields['atm'].queryset = Atm.objects.filter(mfo=mfo)

    class Meta:
        model = ticket
        fields = ('status','description','broken','atm','user')
 
class UpdateUserForm(forms.ModelForm):
    first_name = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')


class UpdateProfileForm(forms.ModelForm):
    photo = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}))
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}))

    class Meta:
        model = Profile
        fields = ('photo', 'bio')

templates/crudapp/atm-detail.html
{% extends 'crudapp/base.html' %}
{% load widget_tweaks %}
{% block content %}

<a href='../' style="float:right;" class="btn btn-secondary"><i class="fas fa-arrow-alt-circle-left"></i> Назад к списку</a>
<a href='/servicedesk/atm/{{obj.id}}/' style="float:right;" class="btn btn-primary mx-2">История заявок</a>
{% if obj.atmModelId.image %}<img style="max-height:75px;max-width:75px;float:left;" src="/media/{{obj.atmModelId.image}}"/>{% endif %}
<h3 class="mt-3">Банкомат - {{object.name}} - {{object.get_workTime_display}}</h3>
<span class="text-muted">{{obj.mfo}}</span>
<div class="card mt-4">
    <div class="card-header">
        <div class="album py-2">
            <div class="portfolio-item row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3">
                    {% for img in imgs %}
                    <div class="col">
                        <div class="card shadow-sm" style="max-width:400px;">
                            <div class="card-header">
                                <small class="text-muted">{{img.uploadedAt}}</small>
                            </div>
                            <a href="{{img.image.url}}" class="popup-btn fancylight" data-fancybox-group="light">
                                <div class="card-body text-muted" style="height:200px;background-size: cover;background-image: url({{img.image.url}});"></div>
                                <!----<img class="img-fluid" src="{{img.image.url}}" style="max-width:400px;" alt="">--->
                            </a>
                        </div>
                    </div>

                    {% endfor %}
            </div>
        </div>
    </div>
    <div class="card-body p-3">
        <ul class="list-group">
            <li class="list-group-item">Модель: <div class="badge bg-dark">{{obj.atmModelId.company}} {{obj.atmModelId.name}}</div></li>
            <li class="list-group-item">Серийный номер: <code>{{obj.serialNumber}}</code></li>
            <li class="list-group-item">Терминал ID: <code>{{obj.terminalId}}</code></li>
            <li class="list-group-item">Мерчант ID: <code>{{obj.merchantId}}</code></li>
            {% if obj.mobile %}<li class="list-group-item">3G/4G: <code>{{obj.mobile}}</code></li>{% endif %}
            {% if obj.inBankProcessing %}<li class="list-group-item">Процессинг: <code>{{obj.get_inBankProcessing_display}}</code></li>{% endif %}
            <li class="list-group-item">NFC: <code>{{obj.get_NFC_display}}</code></li>
            <li class="list-group-item">RDS Commander: <code>{{obj.get_RDSCommander_display}}</code></li>
            {% if obj.exDate %}<li class="list-group-item">Эксплуатация: <code>{{obj.exDate}}</code></li>{% endif %}
            <li class="list-group-item">Геолокация: <code>{{obj.lat}}; {{obj.long}}</code></li>
            <li class="list-group-item"><p class="text-break">{{obj.description}}</p></li>
            <li class="list-group-item" style='min-height:250px;' id='map'></li>
        </ul>
        <input type="hidden" id="id_long" value="{{obj.long}}">
        <input type="hidden" id="id_lat" value="{{obj.lat}}">
    </div>
    <div class="card-footer">
        <div class="btn-group" role="group" style="float:right;">
            <a href="https://maps.yandex.ru/?text={{obj.lat}}+{{obj.long}}" class="btn btn-warning btn-sm"><i class="fas fa-map-marked-alt" target="_blank"></i> Yandex.<b>Maps</b></a>
            <a href="{% url 'photo-upload-num' obj.pk %}" class="btn btn-success btn-sm" target="_blank"><i class="fas fa-camera"></i></a>
            <a href="{% url 'edit' obj.pk %}" class="btn btn-primary btn-sm"><i class="fas fa-edit"></i></a>
            <a href="{% url 'delete' obj.pk %}" class="btn btn-danger btn-sm"><i class="fas fa-trash-alt"></i></a>
        </div>
        {% for f in obj.atmModelId.functions.all %}{{f.html|safe}} {% endfor %}
    </div>
    <script>
        mapboxgl.accessToken = 'pk.eyJ1Ijoic3VpdGUiLCJhIjoiY2t5Mm1kcXp4MG1kcTJ2cGVvMnEzZjdscCJ9.6iIgS8Cz2yR2MSjYc6LuUA';
        const map = new mapboxgl.Map({
        container: 'map', // container id
        style: 'mapbox://styles/mapbox/streets-v11',
        center: [parseFloat(document.getElementById('id_long').value.replace(/,/, '.')), parseFloat(document.getElementById('id_lat').value.replace(/,/, '.'))], // starting position
        zoom: 17 // starting zoom
        });
        var marker = new mapboxgl.Marker({color: "#000000", draggable: true}).setLngLat([parseFloat(document.getElementById('id_long').value.replace(/,/, '.')), parseFloat(document.getElementById('id_lat').value.replace(/,/, '.'))]).addTo(map);
                // $('.portfolio-item').isotope({
        //  	itemSelector: '.item',
        //  	layoutMode: 'fitRows'
        //  });
        // $('.portfolio-menu ul li').click(function(){
        //  	$('.portfolio-menu ul li').removeClass('active');
        //  	$(this).addClass('active');
         	
        //  	var selector = $(this).attr('data-filter');
        //  	$('.portfolio-item').isotope({
        //  		filter:selector
        //  	});
        //  	return  false;
        //  });


    </script>

</div>



{% endblock %}

templates/crudapp/confirm_delete.html
{% extends 'crudapp/base.html' %}
{% block content %}
<h1 class="mt-4">Удалить?</h1>
<br />
<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="alert alert-warning">
            Вы уверены, что хотите удалить <strong>{{ object }}</strong>?
        </div>
    </div>
    <button type="submit" class="btn btn-danger">
        Да
    </button>
    <a href="{% url 'atms' %}" class="btn btn-secondary">Нет</a>
</form>
{% endblock %}

templates/crudapp/edit.html
{% extends 'crudapp/base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="card mt-5">
    <div class="card-header">
        <b>Редактировать</b>
        <a href="{% url 'atms' %}" style="float:right;" class="btn btn-secondary btn-sm"><i class="fas fa-arrow-alt-circle-left"></i> Назад к списку</a>
    </div>
    <form method="post" enctype="multipart/form-data">
        <div class="card-body">
            {% csrf_token %}
            {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
            {% endfor %}
            {% for field in form.visible_fields %}
            <div class="form-group p-2">
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
                {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
            {% endfor %}
            <label for="map-label">Maps:</label>
            <div class="card mb-3">
                <div id='map' style='height:300px;'></div>
                <script>
                    mapboxgl.accessToken = 'pk.eyJ1Ijoic3VpdGUiLCJhIjoiY2t5Mm1kcXp4MG1kcTJ2cGVvMnEzZjdscCJ9.6iIgS8Cz2yR2MSjYc6LuUA';
                    const map = new mapboxgl.Map({
                    container: 'map', // container id
                    style: 'mapbox://styles/mapbox/streets-v11',
                    center: [document.getElementById('id_long').value, document.getElementById('id_lat').value], // starting position
                    zoom: 17 // starting zoom
                    });
                    var markerChange = new mapboxgl.Marker({
                        color: "#000000",
                        draggable: false
                        }).setLngLat([document.getElementById('id_long').value, document.getElementById('id_lat').value]).addTo(map);
                    map.dragRotate.disable();
                    map.on('contextmenu', (e) => {
                    document.getElementById('id_lat').value = e.lngLat.lat;
                    document.getElementById('id_long').value = e.lngLat.lng;
                    markerChange.remove();
                    markerChange = new mapboxgl.Marker({
                        color: "#009900",
                        draggable: false
                        }).setLngLat([e.lngLat.lng, e.lngLat.lat]).addTo(map);
                    });
                </script>
            </div>
        </div>
        <div class="card-footer"><button type="submit" class="btn btn-success">Сохранить</button></div>
    </form>
</div>

{% endblock %}

templates/crudapp/function-delete.html
{% extends 'crudapp/base.html' %}
{% block content %}
<h1 class="mt-4">Удалить?</h1>
<br />
<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="alert alert-warning">
            Вы уверены, что хотите удалить <strong>{{ object }}</strong>?
        </div>
    </div>
    <button type="submit" class="btn btn-danger">
        Да
    </button>
    <a href="{% url 'function-list' %}" class="btn btn-secondary">Нет</a>
</form>
{% endblock %}

templates/crudapp/index.html
{% extends 'crudapp/base.html' %}
{% block content %}

<h3 class="mt-4">Банкоматы</h3>
<br />
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        Список
        <a href="{% url 'create' %}" style="float:right;">
            <button type="button" class="btn btn-success btn-sm"><i class="fas fa-plus-square"></i> Создать</button>
        </a>
    </div>
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Название</th>
                    <th scope="col">Серийный</th>
                    <th scope="col">Модель</th>
                    <th scope="col">Терминал</th>
                    <th scope="col">Мерчант</th>
                    <th scope="col">NFC</th>
                    <th scope="col">Сервис</th>
                    <th scope="col">Функции</th>
                    <th scope="col">Описание</th>
                    <th scope="col">Управление</th>
                </tr>
            </thead>
            <tbody>
                {% for atm in atm_list %}
                <tr>
                    <td>{{ atm.id}}</td>
                    <td class="col-2">
                        <a href="{% url 'detail' atm.pk %}">{{ atm.name }}</a></td>
                    <td>{{ atm.serialNumber}}</td>
                    <td>{{ atm.atmModelId }}</td>
                    <td>{{ atm.terminalId }}</td>
                    <td>{{ atm.merchantId }}</td>
                    <td>{{ atm.mfo }}</td>
                    <td>{{ atm.NFC }}</td>
                    <td>{{ atm.get_service_display }}</td>
                    <td class="col-2">{% for f in atm.atmModelId.functions.all %}{{f.name}} {% endfor %}</td>
                    <td class="col-2">{{ atm.description }}</td>
                    <td class="col-3">
                        <div class="btn-group" role="group" >
                            <a href="https://maps.yandex.ru/?text={{atm.lat}}+{{atm.long}}" class="btn btn-secondary btn-sm" target="_blank"><i class="fas fa-map-marked-alt"></i></a>
                            <a href="{% url 'detail' atm.pk %}" class="btn btn-secondary btn-sm"><i class="fas fa-eye"></i></a>
                            <a href="{% url 'photo-upload-num' atm.pk %}" class="btn btn-secondary btn-sm"><i class="fas fa-camera"></i></a>
                            <a href="{% url 'edit' atm.pk %}" class="btn btn-secondary btn-sm"><i class="fas fa-edit"></i></a>
                            <a href="{% url 'delete' atm.pk %}" class="btn btn-danger btn-sm"><i class="fas fa-trash-alt"></i></a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

templates/crudapp/show-request.html
{% extends 'crudapp/base.html' %}
{% load widget_tweaks %}
{% block content %}

<br />

<div class="card">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        {{object.createdAt}}
        <a href='../' style="float:right;">
            <button type="submit" class="btn btn-sm btn-secondary">Назад к списку</button>
        </a>
    </div>
    <div class="card-body {% if code == 'Ошибка парсинга JSON.' %}bg-danger text-white{% endif %}"><pre><code>{{code}}</code></pre></div>
</div>


{% endblock %}